name: Test

on:
    push:
        branches: ["**"]
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - uses: astral-sh/setup-uv@v8.1.0
              with:
                  cache-dependency-glob: scrape.py

            - name: Run tests
              run: make test
